//------------------------------------------------------------------------------
// <auto-generated>
//     Der Code wurde von einer Vorlage generiert.
//
//     Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten der Anwendung.
//     Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_System_Tut_ecnrypted
{
    using System;
    using System.Collections.Generic;
    
    public partial class Lager
    {
        public int PID { get; set; }
        public string PName { get; set; }
        public string Lagerplatz { get; set; }
        public string Hersteller { get; set; }
        public int Lagerstand { get; set; }
        public string Einheit { get; set; }
    }
}
