//------------------------------------------------------------------------------
// <auto-generated>
//    Dieser Code wurde aus einer Vorlage generiert.
//
//    Manuelle Änderungen an dieser Datei führen möglicherweise zu unerwartetem Verhalten Ihrer Anwendung.
//    Manuelle Änderungen an dieser Datei werden überschrieben, wenn der Code neu generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Login_System_Tut_ecnrypted
{
    using System;
    using System.Collections.Generic;
    
    public partial class lager
    {
        public int PID { get; set; }
        public string Produktbezeichnung { get; set; }
        public string Attribut { get; set; }
        public string Hersteller { get; set; }
        public decimal Lagerbestand { get; set; }
        public string Einheit { get; set; }
        public string Lagerplatz { get; set; }
        public decimal Verkaufspreis { get; set; }
    }
}
